[package]
name = "rpc-proxy"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
clap = { version = "2.32", features = ["yaml"] }
cli = { path = "../proxy/cli" }
env_logger = "0.5"
jsonrpc-core = { git="https://github.com/paritytech/jsonrpc.git"}
jsonrpc-pubsub = { git="https://github.com/paritytech/jsonrpc.git"}
permissioning = { path = "../plugins/permissioning" }
simple-cache = { path = "../plugins/simple-cache" }
tokio = "0.1"
transports = { path = "../proxy/transports" }
upstream = { path = "../plugins/upstream" }
ws-upstream = { path = "../plugins/ws-upstream" }

[[bin]]
name = "rpc-proxy"
path = "bin/rpc-proxy.rs"

[lib]
name = "generic_proxy"
path = "src/lib.rs"
